nodeLinker: node-modules

enableGlobalCache: false

nmMode: hardlinks-local

supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux

checksumBehavior: update

yarnPath: .yarn/releases/yarn-4.5.1.cjs
