[build]
builder = "Dockerfile"
dockerfilePath = "Dockerfile.demo"

[deploy]
startCommand = "python demo-worker.py dev"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.11.6"
