[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python demo-worker.py dev"
healthcheckPath = "/"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10